version: 2
jobs:
  build:
    working_directory: /home/app
    docker:
      - image: docker:19.03.12
    steps:
      - checkout
      - setup_remote_docker
      - run: docker build -t app -f Dockerfile.dev .
  test:
    docker:
      - image: docker:19.03.12
    steps:
      - checkout
      - setup_remote_docker
      - run: docker build -t app -f Dockerfile.dev .
      - run: docker run -e CI=true app npm run test
  deploy:
    docker:
      - image: docker:19.03.12
    steps:
      - checkout
      - run: echo "Hello, World!"

workflows:
  version: 2
  build_test_deploy:
    jobs:
      - build
      - test:
          requires:
            - build 
      - deploy:
          requires:
            - test
