version: 2
jobs:
  build:
    working_directory: /home/app
    docker:
      - image: docker:19.03.12
    steps:
      - checkout
      - setup_remote_docker
      - run: docker build -t $app-prod -f Dockerfile .

workflows:
  version: 2
  build_test_deploy:
    jobs:
      - build

