version: 2
jobs:
  build:
    working_directory: /home/app
    docker:
      - image: docker:19.03.12
    steps:
      - checkout
      - setup_remote_docker
      - run: mkdir -p workspace
      - run: docker build -t ${CIRCLE_WORKFLOW_ID}-app-dev -f Dockerfile.dev .
      - run: docker save ${CIRCLE_WORKFLOW_ID}-app-dev | gzip > workspace/${CIRCLE_WORKFLOW_ID}-app-dev.tar.gz
      # - run: docker save ${CIRCLE_WORKFLOW_ID}-app-dev > workspace/${CIRCLE_WORKFLOW_ID}-app-dev.tar
      - persist_to_workspace:
          root: workspace
          paths:
            - .
  test:
    working_directory: /home/app
    docker:
      - image: docker:19.03.12
    steps:
      - setup_remote_docker
      - attach_workspace:
          at: workspace
      - run: docker load < workspace/${CIRCLE_WORKFLOW_ID}-app-dev.tar.gz
      - run: docker run -e CI=true ${CIRCLE_WORKFLOW_ID}-app-dev npm run test
  deploy:
    working_directory: /home/app
    docker:
      - image: docker:19.03.12
    steps:
      - checkout
      - setup_remote_docker
      - run: docker build -t ${CIRCLE_WORKFLOW_ID}-app-prod .

workflows:
  version: 2
  build_test_deploy:
    jobs:
      # - build
      # - test:
      #     requires:
      #       - build 
      - deploy
