version: 2
jobs:
  build:
    working_directory: /app
    docker:
      - image: docker:19.03.12
    steps:
      - checkout
      - setup_remote_docker
      - run: docker build -t ludovicominto/docker-react -f Dockerfile.dev .
  test:
    docker:
      - image: circleci/ruby:2.4.1
    steps:
      - checkout
      - run: echo "Hello, World!"
  deploy:
    docker:
      - image: circleci/ruby:2.4.1
    steps:
      - checkout
      - run: echo "Hello, World!"

workflows:
  version: 2
  build_test_deploy:
    jobs:
      - build
      - test:
          requires:
            - build 
      - deploy:
          requires:
            - test
